#!/bin/sh -efu

cwd="${0%/*}"
cd "$cwd"

case "$#" in
	0)
		printf 'Usage: swift-deploy /path/to/layout.conf /output/path\n' >&2
		exit 1
		;;
	1)
		printf 'Error: More arguments required\n' >&2
		exit 1
		;;
	[3-9]*)
		printf 'Error: Too many arguments\n' >&2
		exit 1
		;;
esac

layout="$1"; shift
output="$1"; shift

if [ ! -f "$layout" ]; then
	printf '%s: File not found\n' "$layout" >&2
	exit 1
fi

./swift-inventory "$layout" "$output"
ansible-playbook -i "$output"/layout.ini site.yml
