---
- name: Get Swift layout facts
  swift_facts: fn={{ swift_layout }}
  register: swift
  tags: [ "ring", "ring_facts" ]


- name: Get Swift packages
  yum: name={{ item }}
       state=latest
  with_items:
  - openstack-swift
  tags: [ "ring", "ring_packages" ]


- name: Create Swift rings
  swift_ring: fn={{ swift_layout }}
              path={{ swift['layout']['ring_dir'] }}
              norebalance=true
  tags: [ "ring", "ring_create" ]


- name: Rebalance rings
  swift_ring_rebalance: path={{ swift['layout']['ring_dir'] }}
                        name={{ item }}{{ swift['layout']['ring_builder_ext'] }}
  with_items:
  - account
  - container
  - object
  tags: [ "ring", "rebalance_ring" ]
